---
abstract: 'Throwable exceptions for LIMS2'
author:
  - 'Wellcome Trust Sanger Institute'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LIMS2-Exception
requires:
  Data::Dump: 0
  Moose: 0
  MooseX::ClassAttribute: 0
  Throwable::Error: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
version: 0.002
